#=================================================
# https://github.com/P3TERX/Actions-OpenWrt
# Description: Build OpenWrt using GitHub Actions
# Lisence: MIT
# Author: P3TERX
# Blog: https://p3terx.com
#=================================================

name: Repo Dispatcher Test

on: 
  # push: 
  #   branches:
  #     - master
  #schedule:
  #  - cron: 30 15 * * *
  #watch:
  #  types: started
  workflow_dispatch:
    inputs:
      packages:
        description: 'Packages'
        required: false
        default: ''

env:
  REPO_TOKEN: ${{ secrets.REPO_TOKEN }}
  TZ: Asia/Shanghai

jobs:
  build:
    runs-on: ubuntu-latest
    permissions:
      actions: write    
    
    steps:
    - name: Trigger matrix Update
      run: |
        gitdate=$(curl -H "Authorization: token ${{ secrets.REPO_TOKEN }}" -s "https://api.github.com/repos/love-dy/small-package/commits?&per_page=1" | jq -r '.[0].commit.committer.date')
        fpkg="$(echo "${{github.event.inputs.packages}}" | sed -e 's/\(aarch64_generic\|x86_64\|nanopi-r4s\| [0-9][0-9.]*\| ssh\| noser\| cw\)//g' | sed -e 's/ //g')"
        during="$(echo "${{github.event.inputs.packages}}" | grep -o -E ' [0-9][0-9.]*' | sed -e 's/ //')"
        [[ "$fpkg" && ! "$during" ]] || {
          [ "$during" ] || during="1.05"
          durings=`echo "$during*60*60*24" | bc`
          gitdate=$(date -d "$gitdate" +%s)
          now=$(date -d "$(date '+%Y-%m-%d %H:%M:%S')" +%s)
          [ "$during" ] || during="1.05"
          durings=`echo "$during*60*60*24" | bc`
          if [[ $(expr $gitdate + ${durings%.*}) -lt $now ]]; then
            exit;
          fi
        }
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "x86_64 ${{ github.event.inputs.packages }}", "client_payload": {"target": "x86_64"}}'
          curl \
          -X POST https://api.github.com/repos/${{ github.repository }}/dispatches \
          -H "Accept: application/vnd.github.everest-preview+json" \
          -H "Authorization: token ${{ secrets.REPO_TOKEN }}" \
          -d '{"event_type": "aarch64_generic ${{ github.event.inputs.packages }}", "client_payload": {"target": "nanopi-r4s"}}'

    - name: Delete workflow runs
      uses: Mattraks/delete-workflow-runs@main
      continue-on-error: true
      with:
        retain_days: 0
        keep_minimum_runs: 1

